version: "3.8"

services:
  be_adshine:
    image: be-adshine:latest
    container_name: be-adshine
    env_file:
      - .env
    ports:
      - "3022:3000"
    networks:
      - adshine-network
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis-adshine
    environment:
      - REDIS_PASSWORD=myredispassword
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "myredispassword"]
    volumes:
      - redis_data:/data
    networks:
      - adshine-network
  postgres:
    image: postgres:latest
    container_name: postgres-adshine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - adshine-network

volumes:
  redis_data:
  postgres_data:
networks:
  adshine-network:
    driver: bridge